In [2]:
# 讀入 pandas 套件
import pandas as pd
import numpy as np

1. 在 Workshop 1 讀取後的 chipotle 資料框，其中的 `item_price` 欄位有一個 `$` 符號，此欄位被視為字串 (str) 型態，所以無法作數值計算。請單獨取出 item_price 欄位成為一個名為 price 的 Series，再請將此欄位的 `$` 去除，並轉換為 float 資料型態。

In [3]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipotle = pd.read_csv(url, sep='\t')
chipotle.head()
price = [float(value[1:-1]) for value in chipotle.item_price]

2. 請再將 price 取代 chipotle 的 item_price 欄位

In [ ]:
chipotle.item_price = price

3. 請計算 chipotle 前 10 筆資料的 item_price 的加總、平均值、最大值、最小值和標準差

In [ ]:
print(chipotle.item_price[0:10].sum())
print(chipotle.item_price[0:10].mean())
print(chipotle.item_price[0:10].max())
print(chipotle.item_price[0:10].min())
print(chipotle.item_price[0:10].std())

In [5]:
# 7-4 Solution: 請把[1,2,3,4,5,6] 變成 ['1$','2$','3$','4$','5$','6$']
list1 = [1,2,3,4,5,6]
list2 = []
for i in list1:
    list2.append(str(i)+'$')
list2

['1$', '2$', '3$', '4$', '5$', '6$']

In [6]:
# 7-5 Solution: 請把['1$','2$','3$','4$','5$','6$'] 還原為 [1,2,3,4,5,6]
list3 = []
for i in list2:
    i = i.replace('$', '')
    list3.append(int(i))
list3

[1, 2, 3, 4, 5, 6]

In [7]:
# 7-6 Solution: 請將串列 ['A few good man', 'shawshank redemption', 'mission to mars']，利用 zip() 函式顯示如下:
#        0 A few good man
#        1 shawshank redemption
#        2 mission to mars
movies = ['A few good man', 'shawshank redemption', 'mission to mars']
id_movies = range(len(movies))
for i, c in zip(id_movies, movies):
    print(f'id[{i}]:{c}')

id[0]:A few good man
id[1]:shawshank redemption
id[2]:mission to mars


In [8]:
# 7-3 Solution: 請將['Company 1', 'Company 2', 'Company 3']串列轉變為['Company_1', 'Company_2', 'Company_3']
x = ['Company 1', 'Company 2', 'Company 3']
for item in x:
    item = item.replace(' ', '_')
    print(item)

Company_1
Company_2
Company_3


In [9]:
# 7-2 Solution: 請做出串列 [0,3,6,9,12,15,18]的反轉順序[18,15,12,9,6,3,0]
aList = list(range(0, 19, 3))
aList[::-1]

[18, 15, 12, 9, 6, 3, 0]

In [10]:
# 9-1 Solution: 請建立一個資料字典，名稱 pm25，內含台灣六都的 PM2.5 數值，例如 台北市: 20 新北市: 25  桃園市: 32 台中市: 39 台南市: 45 高雄市: 50

pm25 = {
    '台北市': 20,
    '新北市': 25,
    '桃園市': 32,
    '台中市': 39,
    '台南市': 45,
    '高雄市': 50
}

In [11]:
# 9-2 Solution: 請查詢台南市的 PM2.5 數值
pm25['台南市']

45

In [13]:
# 9-3 Solution: 
forever = 'Forever we remain oblivious to the future, \
lost to the past and enduring our torture. \
Forever we take chances to settle our scores, \
losing some battles and winning some wars.'

# 使用 split() 分解 'forever' 字彙
ls = forever.split()

# 使用 set() 算出共有幾個不同的字彙，並存到 keys 變數
keys = set(ls)

# 建立資料字典 dict1，鍵值是 keys 的元素，其值暫為 0
dict1 = {}
for key in keys:
    dict1[key] = 0

# 利用迴圈對應鍵值，對應上鍵值每次將其值加 1
for item in ls:
    if (item in keys):
        dict1[item] = dict1[item] + 1

#  NumPy

In [10]:
# 如果你有一個名為 list1 的 list 物件，共有 6 個元素，分別存放資料如下:
import random
import numpy as np
list1 = random.sample(range(-5, 40), 6)
print('list1: ', list1)
print('type(list1): ', type(list1))

list1:  [27, -1, 10, 39, 29, 19]
type(list1):  <class 'list'>


In [3]:
a = range(0, 100)
random.sample(a, 10)

[37, 39, 32, 49, 34, 38, 13, 5, 84, 59]

In [4]:
# 1) 利用 for loop
degree = []
for c in list1:
    f = (c * 9)/5 + 32
    degree.append(f)
print('轉換後的華氏溫度: ',  degree)

轉換後的華氏溫度:  [53.6, 82.4, 91.4, 46.4, 60.8, 39.2]


In [5]:
# 2) 變形版的 for loop

degree = [(c * 9)/5 + 32 for c in list1]
print('轉換後的華氏溫度: ', degree)

轉換後的華氏溫度:  [53.6, 82.4, 91.4, 46.4, 60.8, 39.2]


In [6]:
# 3) 利用函數轉換攝氏溫度至華氏

def degreeConvert(cDegree):
    fDegree = []
    for c in cDegree:
        f = (c * 9)/5 + 32
        fDegree.append(f)
    return fDegree

In [7]:
# 呼叫 degreConvert 函數
fDegree = degreeConvert(list1)
print('轉換後的華氏溫度: ', fDegree)

轉換後的華氏溫度:  [53.6, 82.4, 91.4, 46.4, 60.8, 39.2]


In [8]:
# 呼叫 degreConvert 函數
fDegree = degreeConvert(list1)
print('轉換後的華氏溫度: ', fDegree)

轉換後的華氏溫度:  [53.6, 82.4, 91.4, 46.4, 60.8, 39.2]


In [ ]:
degree = []
for c in list1:
    degree.append(f(c)) # 呼叫 lambda f，逐筆轉換後回傳
print(degree)

In [11]:
# 1)使用 np.array() 建立一個 3 個元素的 numpy 物件
np1 = np.array([1, 2, 3])
print('np1: ', np1)
print(type(np1))

np1:  [1 2 3]
<class 'numpy.ndarray'>


In [12]:
# 2)從 list 轉換為 numpy array
print('list1: ', list1)
np2 = np.array([list1])
print('np2: ', np2)

list1:  [27, -1, 10, 39, 29, 19]
np2:  [[27 -1 10 39 29 19]]


NumPy Array 的屬性

In [13]:
# 建立 3 個 Numpy array，分別是 1 維, 2 維和 3 維
npx1 = np.random.randint(1, 11, size=6)  # 1 維 array
npx2 = np.random.randint(1, 11, size=(3,4))  # 2 維 (3 x 4) array
npx3 = np.random.randint(1, 11, size=(3, 4, 5))  # 3 維 (3 x 4 x 5) array

In [14]:
print('npx1: ', npx1)
print('npx2: ...')
print(npx2)
print('npx3: ...')
print(npx3)

npx1:  [ 8  2  4 10  6  7]
npx2: ...
[[ 7  3  3  4]
 [ 7 10  4  6]
 [ 9  1  8  8]]
npx3: ...
[[[ 9 10  3  9  7]
  [ 8  6  3  2  2]
  [ 4 10 10 10  5]
  [ 9  7  2  7 10]]

 [[ 3  9  2  8  3]
  [ 9 10 10  6  2]
  [ 4  8 10 10  5]
  [ 9  9  9  4 10]]

 [[ 7  3  1  1  6]
  [ 3  7  9  8  7]
  [ 4  2  5  2  3]
  [ 9  7  1  5  5]]]


In [15]:
# 屬性 
print('npx3.ndim: ', npx3.ndim) # npx3 維度
print('npx3.shape: ', npx3.shape) # 各維度的大小
print('npx3.size: ', npx3.size) # array 的元素大小

npx3.ndim:  3
npx3.shape:  (3, 4, 5)
npx3.size:  60


In [16]:
# 更多屬性 
print('npx3.dtype: ', npx3.dtype) # npx3 array 的資料型態
print('npx3.itemsize: ', npx3.itemsize) # 每一個元素佔據的記憶體大小
print('npx3.nbyes: ', npx3.nbytes) # 總更占用的記憶體大小

npx3.dtype:  int32
npx3.itemsize:  4
npx3.nbyes:  240


Array Indexing (索引): Accessing Single Elements (索引單一元素)

In [17]:
print('npx1: ', npx1)
print('npx1[0] ', npx1[0])
print()
print('npx2: ...')
print(npx2)
print('npx2[0, 1]', npx2[0, 1]) # 第 0 列 第 1 個元素
print('npx2[1, 3]', npx2[1, 3]) # 第 1 列 第 3 個元素

npx1:  [ 8  2  4 10  6  7]
npx1[0]  8

npx2: ...
[[ 7  3  3  4]
 [ 7 10  4  6]
 [ 9  1  8  8]]
npx2[0, 1] 3
npx2[1, 3] 6


In [18]:
# 我們也可以修改 array 內容
print('修改前的 npx1: ', npx1)
npx1[0] = 99
print('修改後的 npx1: ', npx1)

修改前的 npx1:  [ 8  2  4 10  6  7]
修改後的 npx1:  [99  2  4 10  6  7]


In [19]:
print('修改前的 npx2: ...')
print(npx2)
npx2[0, 0] = 99
print()
print('修改後的 npx2: ...')
print(npx2)

修改前的 npx2: ...
[[ 7  3  3  4]
 [ 7 10  4  6]
 [ 9  1  8  8]]

修改後的 npx2: ...
[[99  3  3  4]
 [ 7 10  4  6]
 [ 9  1  8  8]]


In [20]:
print('修改前的 npx3: ...')
print(npx3)
npx3[0, 0, 0] = 99
print()
print('修改後的 npx3: ...')
print(npx3)

修改前的 npx3: ...
[[[ 9 10  3  9  7]
  [ 8  6  3  2  2]
  [ 4 10 10 10  5]
  [ 9  7  2  7 10]]

 [[ 3  9  2  8  3]
  [ 9 10 10  6  2]
  [ 4  8 10 10  5]
  [ 9  9  9  4 10]]

 [[ 7  3  1  1  6]
  [ 3  7  9  8  7]
  [ 4  2  5  2  3]
  [ 9  7  1  5  5]]]

修改後的 npx3: ...
[[[99 10  3  9  7]
  [ 8  6  3  2  2]
  [ 4 10 10 10  5]
  [ 9  7  2  7 10]]

 [[ 3  9  2  8  3]
  [ 9 10 10  6  2]
  [ 4  8 10 10  5]
  [ 9  9  9  4 10]]

 [[ 7  3  1  1  6]
  [ 3  7  9  8  7]
  [ 4  2  5  2  3]
  [ 9  7  1  5  5]]]


In [21]:
npx2 = np.random.randint(1, 101, size=(3, 4))
print('npx2: ...')
print(npx2)
print('-'*30)

print('npx2[0:2, 0:2]...') # 取出第 0 到第 1 列的第 0 到第 1 行的資料
print(npx2[0:2, 0:2])
print('-'*30)

print('npx2[1:3, 2:4]...') # 取出第 1 到第 2 列的第 2 到第 3 行的資料
print(npx2[1:3, 2:4])
print('-'*30)

print('npx2[(0,2), 0:2]...') # 取出第 0 和第 2 列的第 0 到第 2 行的資料
print(npx2[(0,2), 0:2])
print('-'*30)

print('npx2[:3, :]...') # 取出第 0 至第 1 列的第 1 到最後行的資料
print(npx2[:2, 1:])
print('-'*30)

npx2: ...
[[47  2 61 60]
 [56 27 61 98]
 [52 24 18 65]]
------------------------------
npx2[0:2, 0:2]...
[[47  2]
 [56 27]]
------------------------------
npx2[1:3, 2:4]...
[[61 98]
 [18 65]]
------------------------------
npx2[(0,2), 0:2]...
[[47  2]
 [52 24]]
------------------------------
npx2[:3, :]...
[[ 2 61 60]
 [27 61 98]]
------------------------------


In [22]:
print('npx2: ...')
print(npx2)
print('-'*30)
print('npx2[:, 0]: ', npx2[:, 0]) # 單獨取出第 0 行
print('npx2[0, :]: ', npx2[0, :]) # 單獨取出第 0 列
print('npx2[1, :]: ', npx2[1, :]) # 單獨取出第 1 列

npx2: ...
[[47  2 61 60]
 [56 27 61 98]
 [52 24 18 65]]
------------------------------
npx2[:, 0]:  [47 56 52]
npx2[0, :]:  [47  2 61 60]
npx2[1, :]:  [56 27 61 98]


NumPy array 有⼀個重要的預設特性稱為「不複製」，因此不論在切割或重新宣告的情境中都是創建陣列的 View，⽽⾮複製另⼀個陣列，這代表著對以 View 型式存在的⼦陣列（Subarray更新會改動到原始陣列)

In [23]:
print('npx1: ', npx1)
print('-'*30)

print('npx1_view = npx1[0:5]')
npx1_view = npx1[0:5]
print('npx1_view: ', npx1_view)
print('-'*30)
print('修改為 npx1[0] = 100 ...')
npx1_view[0] = 100
print('修改後 npx1_view: ', npx1_view)
print('即使沒有修改 npx1，但 npx1 也會跟著改變...')
print('npx1: ', npx1)

npx1:  [99  2  4 10  6  7]
------------------------------
npx1_view = npx1[0:5]
npx1_view:  [99  2  4 10  6]
------------------------------
修改為 npx1[0] = 100 ...
修改後 npx1_view:  [100   2   4  10   6]
即使沒有修改 npx1，但 npx1 也會跟著改變...
npx1:  [100   2   4  10   6   7]


In [24]:
print('npx2: ...')
print(npx2)
print('-'*30)

print('拷貝 npx2 給 npx2_copy...')
npx2_copy = npx2.copy()
print('npx2_copy ...')
print(npx2_copy)

npx2: ...
[[47  2 61 60]
 [56 27 61 98]
 [52 24 18 65]]
------------------------------
拷貝 npx2 給 npx2_copy...
npx2_copy ...
[[47  2 61 60]
 [56 27 61 98]
 [52 24 18 65]]


In [25]:
# 現在修改 npx2_copy，但不會影響 npx2，因為兩者是不同的物件
npx2_copy[0,0] = 100
print('npx2_copy: ...')
print(npx2_copy)
print('-'*30)

print('npx2: ...')
print(npx2)

npx2_copy: ...
[[100   2  61  60]
 [ 56  27  61  98]
 [ 52  24  18  65]]
------------------------------
npx2: ...
[[47  2 61 60]
 [56 27 61 98]
 [52 24 18 65]]


重新改變陣列維度 (Reshaping of Arrays)

In [26]:
np3 = np.random.randint(1, 101, size=18)
print('np3: ', np3) # 1 維陣列 np3 有 18 個元素

np3:  [48  1 47  2 49 90  1 13 61 63 16 98 77 87 61 13 24 21]


In [27]:
# reshape np3 成為 2 維陣列
np3_2d = np3.reshape(3, 6)
print('np3_2d: ...') # 將 np3 陣列更改為 3 x 6 的 2 維陣列
print(np3_2d)

np3_2d: ...
[[48  1 47  2 49 90]
 [ 1 13 61 63 16 98]
 [77 87 61 13 24 21]]


In [28]:
# reshape np3 成為 3 維陣列
np3_3d = np3.reshape(2, 3, 3)
print('np3_3d: ...') # 將 np3 陣列更改為 2 x 3 x 3 的 3 維陣列
print(np3_3d)

np3_3d: ...
[[[48  1 47]
  [ 2 49 90]
  [ 1 13 61]]

 [[63 16 98]
  [77 87 61]
  [13 24 21]]]


In [29]:
# 使用 concatenate() 合併 1 維陣列
x1 = np.array([1, 2, 3])
y1 = np.array([3, 2, 1])
z1 = np.concatenate([x1, y1])
print('z1: ', z1)

z1:  [1 2 3 3 2 1]


In [30]:
# 使用 concatenate() 合併 2 維陣列
x2 = np.random.randint(1, 11, size=(2,3))
y2 = np.random.randint(1, 11, size=(2,3))
print('x2...')
print(x2)
print('y2...')
print(y2)
print()

x2...
[[ 2  7  6]
 [ 5  5 10]]
y2...
[[10  7  8]
 [ 1  3  6]]



In [31]:
z2 = np.concatenate([x2, y2], axis=0) # 以 "列" 的方向合併
print('z2 以 "列" 的方向合併...')
print(z2)

z3 = np.concatenate([x2, y2], axis=1) # 以 "行" 的方向合併
print('z3 以 "行" 的方向合併...')
print(z3)

z2 以 "列" 的方向合併...
[[ 2  7  6]
 [ 5  5 10]
 [10  7  8]
 [ 1  3  6]]
z3 以 "行" 的方向合併...
[[ 2  7  6 10  7  8]
 [ 5  5 10  1  3  6]]


若兩個 arrays 的維度不一致，可使用 vstack() 或 hstack() 處理

In [32]:
# x1 是 1 維陣列； y1 是 2 維陣列
x1 = np.array([1, 2, 3])
y1 = np.array([[4, 5, 6], [7, 8, 9]])

print('x1: ', x1)
print('y1: ... ')
print(y1)

x1:  [1 2 3]
y1: ... 
[[4 5 6]
 [7 8 9]]


In [33]:
#使用 vstack() 將 x1 和 y1 以 "列" 的方向合併
print('np.vstack([x1, y1])...')
print(np.vstack([x1, y1]))
print('-'*30)

x1 = np.array([[1],[2]])
print('x1: ...')
print(x1)
print('y1: ... ')
print(y1)
# 使用 vstack() 將 x1 和 y1 以 "列" 的方向合併
print('np.hstack([x1, y1])...')
print(np.hstack([x1, y1]))


np.vstack([x1, y1])...
[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------
x1: ...
[[1]
 [2]]
y1: ... 
[[4 5 6]
 [7 8 9]]
np.hstack([x1, y1])...
[[1 4 5 6]
 [2 7 8 9]]


陣列的分割 (Splitting of Array)
陣列的分割可選擇以 "列" 的方向分割，或選擇以 "行" 的方向分割

np.split()
np.vsplit()
np.hsplit()

In [34]:
# 一維陣列的分割
arrd1 = np.arange(1, 11) 
print('arr: ', arrd1)

# 分割 arrd1 成為 3 個 subarrays, arr0, arr1, arr2
# arr0=arrd[0, 2]; arr1=[3, 5]; arr2[5, :]
#arr0, arr1, arr2= np.split(arrd1, [2, 5])
arr0, arr1, arr2= np.split(arrd1, [3, 7])
print('arr0: ', arr0)
print('arr1: ', arr1)
print('arr2: ', arr2)

arr:  [ 1  2  3  4  5  6  7  8  9 10]
arr0:  [1 2 3]
arr1:  [4 5 6 7]
arr2:  [ 8  9 10]


In [35]:
# 二維陣列的分割
arrd2 = np.arange(1, 17).reshape(4,4)
print('arrd2: ...')
print(arrd2)

# 垂直分割 arrd2 成為 upper 及 lower
# upper=arrd2[0:2]; lower=arrd2[2:4, :]
upper, lower = np.vsplit(arrd2, 2)
print('upper: ...')
print(upper)
print('lower: ...')
print(lower)

# 水平分割 arrd2 成為 lpart 及 rpart
lpart, rpart = np.hsplit(arrd2, 2)
print('lpart: ...')
print(lpart)
print('rpart: ...')
print(rpart)

arrd2: ...
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
upper: ...
[[1 2 3 4]
 [5 6 7 8]]
lower: ...
[[ 9 10 11 12]
 [13 14 15 16]]
lpart: ...
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
rpart: ...
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


In [36]:
# Create a length-10 integer array filled with zeros
zero = np.zeros(10, dtype=int)
print(zero)

[0 0 0 0 0 0 0 0 0 0]


In [37]:
# Create a 3x5 floating-point array filled with ones
ones = np.ones((3, 5), dtype=float)
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [38]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
npArange = np.arange(0, 20, 2)
print('np.arange(0, 20, 2): ', npArange)
print('type: ', type(npArange))
print('-'*30)

pRange = range(0, 20, 2)
print('range(0, 20, 2): ', list(pRange))
print('type: ', type(pRange))

np.arange(0, 20, 2):  [ 0  2  4  6  8 10 12 14 16 18]
type:  <class 'numpy.ndarray'>
------------------------------
range(0, 20, 2):  [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
type:  <class 'range'>


In [39]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [40]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.71820992, 0.39618105, 0.85943444],
       [0.95318482, 0.55878441, 0.63534421],
       [0.55652679, 0.76146583, 0.46029553]])

In [41]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
nd = np.random.normal(0, 1, (3, 3))
print(nd)
print('-'*40)
# 如果想要每次執行都有相同的結果，必須設定亂數 seed
nps = np.random.RandomState(seed=100)
print(nps.normal(0, 1, (3, 3)))
print('-'*40)
nps = np.random.RandomState(seed=100)
print(nps.normal(0, 1, (3, 3)))

[[ 0.60745029  0.10180186 -1.26028192]
 [ 3.18471804 -0.97103394 -0.64908525]
 [-0.92707271 -0.48407973 -0.48318084]]
----------------------------------------
[[-1.74976547  0.3426804   1.1530358 ]
 [-0.25243604  0.98132079  0.51421884]
 [ 0.22117967 -1.07004333 -0.18949583]]
----------------------------------------
[[-1.74976547  0.3426804   1.1530358 ]
 [-0.25243604  0.98132079  0.51421884]
 [ 0.22117967 -1.07004333 -0.18949583]]


另有一個和 random.normal() 類似的函式 - random.randn()
random.randn() 設定 mean = 0, standard deviation = 1 不能改變，
但 random.normal() 預設雖是 mean=0, standard deviation=1, 但可以調整平均值和標準差，¶

In [42]:
nps = np.random.RandomState(seed=100)
print(nps.normal(5, 10, (3, 3))) # mean=5, standard deviation=10
print('-'*30)
print(nps.randn(3, 3)) # mean=0, standard deviation=1

[[-12.49765473   8.42680403  16.53035803]
 [  2.47563963  14.81320787  10.14218841]
 [  7.21179669  -5.70043331   3.10504169]]
------------------------------
[[ 0.25500144 -0.45802699  0.43516349]
 [-0.58359505  0.81684707  0.67272081]
 [-0.10441114 -0.53128038  1.02973269]]


In [43]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

In [45]:
# 一些 NumPy Array 的小技巧
#--- 1.字串合併 ---#
#x1 = np.array([1, 2, 3])
#x2 = np.array([4, 5, 6])
x1 = np.array(['a','b'])
x2 = np.array(['c','d'])
print(np.char.add(x1,x2))

['ac' 'bd']


In [46]:
#--- 2.字串倍數相乘 ---#
x3 = 'Hello '
print(np.char.multiply(x3, 3))

Hello Hello Hello 


In [47]:
#--- 3.第 1 個字母大寫 ---#
x4 = 'this is a outstanding sotry..'
print(np.char.capitalize(x4))

This is a outstanding sotry..


In [48]:
#--- 4.第 1 個字母大寫 ---#
print(np.char.title(x4)) # first letter to capital

This Is A Outstanding Sotry..


In [49]:
#--- 5.每個字母小寫 ---#
print(np.char.lower(['HELLO, WORLD']))
print(np.char.lower('HELLO, World'))

['hello, world']
hello, world


In [50]:
#--- 6.每個字母大寫 ---#
print(np.char.upper(['python', 'data']))
print(np.char.upper('python is easy'))

['PYTHON' 'DATA']
PYTHON IS EASY


In [51]:
#-- 7.切割每個文字 ---#
word = 'are you coming to the party?'
words = np.char.split(word)
print(words)

['are', 'you', 'coming', 'to', 'the', 'party?']


In [52]:
#-- 8.切割每一列文字 ---#
word = 'hello\nare you coming to the \nparty?'
words = np.char.splitlines(word)
print(words)

['hello', 'are you coming to the ', 'party?']


In [53]:
#-- 9.去除頭尾的贅字 ---#
word = ['ninan', 'admin', 'anaitan']
print(np.char.strip(word, 'n'))

['ina' 'admi' 'anaita']


In [54]:
#-- 10.合併字串 ---#
print(np.char.join([':','-'],['dmy','ymd'])) # join strings

['d:m:y' 'y-m-d']


In [55]:
#-- 11.文字取代 ---#
print(np.char.replace(['He is a good dancer'], 'is', 'was')) # subtitute 'is' to 'was'

['He was a good dancer']


# Function

In [57]:
# 定義一個函數名稱 my_function2
# my_function2 有一個參數 name，函數的工作就是印出 name 參數

def my_function2(name):
    print(name)

In [58]:
# 呼叫函數 my_function2，傳入 aList 參數
aList = ['Apple', 'banana', 'orange']
for item in aList:
    my_function2(item)

Apple
banana
orange


函數的參數有兩種使用情況
1.fixed number of arguments (固定參數數目)
2.arbitrary number of arguments (不固定參數數目)

In [59]:
# 定義一個函數名稱 my_function3()，有 2 個參數
def my_function3(num1, num2):
    return num1 + num2

In [60]:
# 呼叫函數 my_function3，傳入 2 個參數
x1 = 10
x2 = 20
print('my_function3(x1, x2) = ', my_function3(x1, x2))

my_function3(x1, x2) =  30


In [61]:
# Arbitrary Arguments (不固定參數數目)
def my_function4(*args):
    sum = 0
    for x in args:
        sum += x
    return sum

In [62]:
# 呼叫函數 my_function4
print(my_function4(10, 20))

print(my_function4(10, 20, 30))

30
60


In [63]:
# Keyword Arguments (指定參數名稱，表示參數的順序不同，但可以用參數名稱對應)
def my_function5(child1, child2, child3):
    result = child1 + " " + child2 + " " + child3
    return result

In [64]:
# 呼叫函數 my_function5
result = my_function5(child3='GHI', child2='DEF', child1='ABC') # 指定參數名稱
print(result)

result = my_function5(child2='DEF', child1='ABC', child3='GHI') # 指定參數名稱
print(result)

ABC DEF GHI
ABC DEF GHI


In [65]:
# Arbitrary Keyword Arguments, **kwargs
# 當不知道有多少 keywords arguments 時可以使用此方法
def my_function6(**kwargs):
    print('kwargs type: ', type(kwargs)) # kwargs is a dictionary object
    for item in kwargs:
        print('item[{}]={}'.format(item, kwargs[item]))

In [66]:
my_function6(A1='GHI', A2='DEF', A3='ABC', A4='XYZ')

kwargs type:  <class 'dict'>
item[A1]=GHI
item[A2]=DEF
item[A3]=ABC
item[A4]=XYZ


In [67]:
# 預設參數值 (Default Parameter Value)
# 此題預設參數值是 'Taiwan'
def my_function7(country = "Taiwan"):
    print("I am from " + country)

my_function7('USA')
my_function7()

I am from USA
I am from Taiwan


In [68]:
# 遞迴函數 (Recursion)
def tri_recursion(k):
    if (k > 0):
        result = k + tri_recursion(k-1)
        #print(result)
    else:
        result = 0
    return result

In [69]:
tri_recursion(5)

15

lambda 函數
lambda 函數主要目的是要快速定義一個函數，不需要函數名稱。
lambda 函數可以有許多參數，但只有一行程式碼。
lambda 函數運算式的計算結果會自動傳回來，不需要使用return指令
Lambda函數不能夠使用指定運算子，也不可以有迴圈

In [70]:
# 定義一個 lambda 函數，此函數會將傳遞的參數 * 2
result = lambda x: x * 2
print(result(10))

20


In [71]:
# 定義一個 lambda 函數，此函數有 2 個參數|
result = lambda x, y: x + y
print(result(10, 20))

30


In [72]:
# 定義一個 lambda 函數，此函數比較兩個參數的大小
f = lambda num1, num2: num1 if num1 > num2 else num2
print(f(100, 200))

200


In [73]:
# 方法 1: 使用 for 迴圈，逐筆選出
scores = [90, 50, 80, 40, 100]
result = []
for score in scores:
    if score < 60:
        result.append(score)
print(result)

[50, 40]


In [74]:
# 方法 2: 自訂函數搭配內建 filter() 函數
# 自訂函數 qlyScore()
scores = [90, 50, 80, 40, 100]
def qlyScore(x):
    if x < 60:
        return True
    else:
        return False
    
result = filter(qlyScore, scores)
print(list(result))

[50, 40]


In [75]:
# 方法 3: 使用 lambda 函數搭配內建 filter() 函數
#f = lambda x: True if x < 60 else False
#result = filter(f, scores)
result = filter(lambda x: True if x<60 else False, scores)
print(list(result))

[50, 40]


In [76]:
# 方法 4: 使用 numpy 套件
import numpy as np
np1 = np.array(scores)
np1[np1 < 60]

array([50, 40])

例外處理 (Exception Handling)
當程式發生錯誤，或是呼叫 exception，Python 程式會停止執行，並且產生錯誤訊息。
例外處理主要由 try 和 except 兩個主要指令，外加選擇性的 else 和 finally 指令。
try 區塊檢驗程式碼是否有錯誤的區塊。
except 區塊是處理程式碼錯誤的區塊。
finally 區塊是不論程式是否發生有錯，一定要執行的區塊。

try... except... finally 語法
try:
    # 想要執行但可能引發錯誤的程式區塊
except: 例外錯誤類型1 [as 參數]:     # [as 參數] 可省略 
    # 發生例外錯誤類型1 的程式
except: 例外錯誤類型2 [as 參數]:     # [as 參數] 可省略 :
    # 發生例外錯誤類型2 的程式
except Exception [as 參數]:     # [as 參數] 可省略 : 
    # 處理上面未捕捉，但其它可能發生的錯誤
finally:
    # 不管有無錯誤，最後都會執行

In [77]:
# try-except-finally 範例
try:
  a, b = input('請輸入兩個整數(空格隔開): ').split()
  a = int(a)
  b = int(b)
  print('兩個整數相除結果: ', a/b)
except ZeroDivisionError as error1:
  print("被除數是 0 的狀況!... ", error1)
except ValueError as error2:
  print('輸入資料的型態錯誤!... ', error2)
finally:
    print('處理完畢!')

請輸入兩個整數(空格隔開): 123
輸入資料的型態錯誤!...  not enough values to unpack (expected 2, got 1)
處理完畢!


In [78]:
import random 
from datetime import datetime
temperature = random.randint(10, 40) # 溫度最高 40 度，最低 10 度
humidity = random.randint(30, 100)   # 濕度最高 40 度，最低 10 度
current = datetime.now()
currentTime = current.strftime('%Y-%m-%d %H:%M:%S')
print('日期時間, 溫度,  濕度\n')
file = open('weatherTest.txt', 'a')
file.write('日期時間, 溫度, 濕度\n')
weather = currentTime + ',' + str(temperature) + ',' + str(humidity) + '\n'
file.write(weather)
print(weather)
file.close()

日期時間, 溫度,  濕度

2020-04-12 15:25:22,34,70



In [79]:
file = open('weatherTest.txt', 'r', encoding='cp950')
tmp = file.read()
file.close()
print(tmp)

日期時間, 溫度, 濕度
2020-04-12 15:25:22,34,70

