In [2]:
import numpy as np
import pandas as pd
arr = np.array(("Monkey D. Luffy", "Roronoa Zoro", "Nami", "Usopp", "Vinsmoke Sanji", "Tony Tony Chopper", "Nico Robin", "Franky", "Brook"))

In [87]:
idx = []
for i in range(9):
    idx.append("a" + str(i + 1))
ser = pd.Series(arr, index = idx)
print(ser)

a1      Monkey D. Luffy
a2         Roronoa Zoro
a3                 Nami
a4                Usopp
a5       Vinsmoke Sanji
a6    Tony Tony Chopper
a7           Nico Robin
a8               Franky
a9                Brook
dtype: object


In [4]:
ser = pd.Series(arr) # 預設的索引是從 0 至  8 順序編號
ser

0      Monkey D. Luffy
1         Roronoa Zoro
2                 Nami
3                Usopp
4       Vinsmoke Sanji
5    Tony Tony Chopper
6           Nico Robin
7               Franky
8                Brook
dtype: object

In [5]:
crew_dict = {
    "captain": "Monkey D. Luffy",
    "swordsman": "Roronoa Zoro",
    "navigator": "Nami",
    "sniper": "Usopp",
    "chef": "Vinsmoke Sanji",
    "doctor": "Tony Tony Chopper",
    "archaeologist": "Nico Robin",
    "shipwright": "Franky",
    "musician": "Brook"
}

In [6]:
ser = pd.Series(crew_dict) # 會依照 crew_dict 的 key 值排序
ser

captain            Monkey D. Luffy
swordsman             Roronoa Zoro
navigator                     Nami
sniper                       Usopp
chef                Vinsmoke Sanji
doctor           Tony Tony Chopper
archaeologist           Nico Robin
shipwright                  Franky
musician                     Brook
dtype: object

In [7]:
ser['captain']#也可多重選取

'Monkey D. Luffy'

In [8]:
ser[[0, 3, 6]]

captain          Monkey D. Luffy
sniper                     Usopp
archaeologist         Nico Robin
dtype: object

In [9]:
# 建立一個 Series 物件
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
print(data)

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64


In [11]:
data['a']

0.25

In [12]:
# 取出 index 
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [13]:
# 取出元素值
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [14]:
# 取出每一個成對的索引和元素內容
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [17]:
# 新增索引和元素內容
data['e'] = 1.5
data['e']

1.5

In [16]:
# slicing by explicit index (明確的索引，透過索引值來取出資料)
data['b':'d']

b    0.50
c    0.75
d    1.00
dtype: float64

In [18]:
#遮罩
mask = (data > 0.3) & (data < 0.8)
print(mask)

a    False
b     True
c     True
d    False
e    False
dtype: bool


In [19]:
print('-'*30)
print(data[mask]) # 選取True的元素，過濾掉回傳False的元素

------------------------------
b    0.50
c    0.75
dtype: float64


In [20]:
x = np.random.randint(100, size=10)
print(x)

[33 30 19  6 45 56 90 34 90 20]


In [22]:
ind = [3, 7, 4]
print(x[ind])
print('-'*30)
# 另一個寫法
print(x[[3, 7, 4]]) 

[ 6 34 45]
------------------------------
[ 6 34 45]


In [23]:
idx = ['a','b']
print(data[idx])
print('-'*30)
print(data[['a','b']])

a    0.25
b    0.50
dtype: float64
------------------------------
a    0.25
b    0.50
dtype: float64


In [24]:
inx = np.array([[0, 1], [2, 3]])
x[inx]

array([[33, 30],
       [19,  6]])

In [162]:
# 直接從 URL 讀取資料集 Chiporders，並存入 orders 資料框 (DataFrame)
orders = pd.read_table('http://bit.ly/chiporders')

In [148]:
# 查看前 5 筆的 orders 資料
orders.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

In [163]:
#在 Workshop 1 讀取後的 chipotle 資料框，其中的 item_price 欄位有一個 $ 符號，此欄位被視為字串 (str) 型態，所以無法作數值計算。
#請單獨取出 item_price 欄位成為一個名為 price 的 Series，再請將此欄位的 $ 去除，並轉換為 float 資料型態。

#要先將值取出來，再統一去掉$號，最後將統一的版本丟到新的欄位中
#orders.keys()
orders['price']=orders['item_price'].str.replace('$','')
orders['price']=orders['price'].astype(float)
orders

order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
...        ...       ...                                    ...   
4617      1833         1                          Steak Burrito   
4618      1833         1                          Steak Burrito   
4619      1834         1                     Chicken Salad Bowl   
4620      1834         1                     Chicken Salad Bowl   
4621      1834         1                     Chicken Salad Bowl   

                                     choice_description item_price  price  
0                                                   NaN     $2.39    2.39  
1                                          [Clementine]     $3.39    3.39  
2                                               [Apple]     $3.39    3.39  
3                                                   NaN     $2.39    2.39  
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   16.98  
...                                                 ...        ...    ...  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75   11.75  
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75   11.75  
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25   11.25  
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75    8.75  
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75    8.75  

[4622 rows x 6 columns]

In [164]:
#請再將 price 取代 chipotle 的 item_price 欄位
orders=orders.drop(labels=['item_price'],axis='columns')
orders

order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
...        ...       ...                                    ...   
4617      1833         1                          Steak Burrito   
4618      1833         1                          Steak Burrito   
4619      1834         1                     Chicken Salad Bowl   
4620      1834         1                     Chicken Salad Bowl   
4621      1834         1                     Chicken Salad Bowl   

                                     choice_description  price  
0                                                   NaN   2.39  
1                                          [Clementine]   3.39  
2                                               [Apple]   3.39  
3                                                   NaN   2.39  
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...  16.98  
...                                                 ...    ...  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...  11.75  
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...  11.75  
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...  11.25  
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...   8.75  
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...   8.75  

[4622 rows x 5 columns]

In [55]:
#請計算 chipotle 前 10 筆資料的 item_price 的加總、平均值、最大值、最小值和標準差。
x=orders['price'].head(10)
x.describe()

count    10.00000
mean      7.14600
std       5.21408
min       1.69000
25%       2.64000
50%       6.32000
75%      10.54750
max      16.98000
Name: price, dtype: float64

In [63]:
#請選出 item_price 大於 30 的資料
mask = (orders['price'] > 30)
orders=orders[mask]
orders

order_id  quantity                     item_name  \
409        178         3                  Chicken Bowl   
1254       511         4               Chicken Burrito   
3480      1398         3                 Carnitas Bowl   
3598      1443        15  Chips and Fresh Tomato Salsa   
3601      1443         3                Veggie Burrito   
3602      1443         4               Chicken Burrito   

                                     choice_description  price  
409   [[Fresh Tomato Salsa (Mild), Tomatillo-Green C...  32.94  
1254  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...  35.00  
3480  [Roasted Chili Corn Salsa, [Fajita Vegetables,...  35.25  
3598                                                NaN  44.25  
3601  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...  33.75  
3602  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...  35.00

In [64]:
df1 = pd.Series(['aa', 'bb', 'cc', 'dd', 'ee'], index=[1, 2, 3, 4, 5])
print(df1)

1    aa
2    bb
3    cc
4    dd
5    ee
dtype: object


In [66]:
# explicit index (明確的索引，透過索引值來取出資料)
print(df1[1]) 

aa


In [67]:
print(df1[1:3])

2    bb
3    cc
dtype: object


In [189]:
df2.loc['a']

345

In [68]:
# loc explicit  (明確的索引方式)
print('df1.loc[1]: ', df1.loc[1]) # indexing

df1.loc[1]:  aa


In [191]:
#df2.iloc['a'] 不可行

In [69]:
print(df1.loc[1:3])

1    aa
2    bb
3    cc
dtype: object


In [70]:
# iloc implicit (隱含的索引方式)
print('df1.iloc[1]: ', df1.iloc[1]) # indexing
print('-'*30)
print('df1.iloc[1:3]...')           # slicing
print(df1.iloc[1:3])

df1.iloc[1]:  bb
------------------------------
df1.iloc[1:3]...
2    bb
3    cc
dtype: object


In [72]:
df2 = pd.Series([345, 876, 742, 212, 456], index=['a', 'b', 'c', 'd', 'e'])
print(df2)

a    345
b    876
c    742
d    212
e    456
dtype: int64


In [73]:
df3 = pd.Series([345, 876, 742, 212, 456])
df3

0    345
1    876
2    742
3    212
4    456
dtype: int64

In [77]:
#print(df2['a':'c'])
#df2.loc['a':'c']
df2.iloc[0:4]

a    345
b    876
c    742
d    212
dtype: int64

In [160]:
#chipotle 資料框共有 4622 筆資料，預設索引值(index)從 0 一直到 4621。請將索引值更改為 'a1' 到 'a4622'。

#ser = pd.Series(arr, index = idx)
#order.index.map[]
idx = {}
for i in range(4622):
    idx[i]=("a" + str(i + 1))
    
order=orders.rename(index=idx)
order

order_id  quantity                              item_name  \
a1            1         1           Chips and Fresh Tomato Salsa   
a2            1         1                                   Izze   
a3            1         1                       Nantucket Nectar   
a4            1         1  Chips and Tomatillo-Green Chili Salsa   
a5            2         2                           Chicken Bowl   
...         ...       ...                                    ...   
a4618      1833         1                          Steak Burrito   
a4619      1833         1                          Steak Burrito   
a4620      1834         1                     Chicken Salad Bowl   
a4621      1834         1                     Chicken Salad Bowl   
a4622      1834         1                     Chicken Salad Bowl   

                                      choice_description  price  
a1                                                   NaN   2.39  
a2                                          [Clementine]   3.39  
a3                                               [Apple]   3.39  
a4                                                   NaN   2.39  
a5     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...  16.98  
...                                                  ...    ...  
a4618  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...  11.75  
a4619  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...  11.75  
a4620  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...  11.25  
a4621  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...   8.75  
a4622  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...   8.75  

[4622 rows x 5 columns]

In [183]:
#請用 loc 方法取出 chipotle 介於 'a100' 至 'a105' 之資料。也請再用 iloc 取出相同筆數的資料。
order.head(5)
order.loc['a100':'a105']

order_id  quantity            item_name  \
a100        44         1         Chicken Bowl   
a101        44         1  Chips and Guacamole   
a102        45         1        Steak Burrito   
a103        45         1           Steak Bowl   
a104        45         1  Chips and Guacamole   
a105        46         1       Veggie Burrito   

                                     choice_description  price  
a100  [Tomatillo Red Chili Salsa, [Rice, Fajita Vege...   8.75  
a101                                                NaN   4.45  
a102  [Tomatillo-Green Chili Salsa (Medium), [Rice, ...   8.99  
a103  [Tomatillo-Green Chili Salsa (Medium), [Rice, ...   8.99  
a104                                                NaN   3.99  
a105  [Fresh Tomato Salsa (Mild), [Black Beans, Rice...   8.49

In [184]:
order.iloc[99:105]

order_id  quantity            item_name  \
a100        44         1         Chicken Bowl   
a101        44         1  Chips and Guacamole   
a102        45         1        Steak Burrito   
a103        45         1           Steak Bowl   
a104        45         1  Chips and Guacamole   
a105        46         1       Veggie Burrito   

                                     choice_description  price  
a100  [Tomatillo Red Chili Salsa, [Rice, Fajita Vege...   8.75  
a101                                                NaN   4.45  
a102  [Tomatillo-Green Chili Salsa (Medium), [Rice, ...   8.99  
a103  [Tomatillo-Green Chili Salsa (Medium), [Rice, ...   8.99  
a104                                                NaN   3.99  
a105  [Fresh Tomato Salsa (Mild), [Black Beans, Rice...   8.49